name = "injured-workers-unite"
compatibility_date = "2025-11-14"

[pages]
build_command = "npm run build"
build_output_dir = "out"

[env.production]
name = "injured-workers-unite"

# Build environment variables
[env.production.vars]
STATIC_EXPORT = "true"
